[alias]
# c = "clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used"
c = "clippy -- -W clippy::pedantic -W clippy::nursery"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

